[build-system]
requires = ["setuptools >= 42.0", "wheel"]
build-backend = "setuptools.build_meta"

# [build-system]
# requires = ["setuptools >= 42.0", "wheel",]
# build-backend = "setuptools.build_meta"

[project]
name = "GhettoRecorder"
version = "2.4.7"
description = "multiprocessor capable internet radio grabber"
authors = [{name = "René Horn", email = "rene_horn@gmx.net" }]
keywords = ['internet radio grabber']
license = {text = "MIT"}
readme = "README.rst"
requires-python = ">=3.7"


classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Multimedia :: Sound/Audio :: Capture/Recording",
]
dependencies = [
	"aacRepair",
	"certifi",
]

[project.urls]
homepage = "https://github.com/44xtc44"
documentation = "https://GhettoRecorder.readthedocs.io/"
repository = "https://github.com/44xtc44/GhettoRecorder"

